# Generated by Django 5.2 on 2025-04-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("user_email", models.EmailField(max_length=254)),
                ("user_age", models.IntegerField()),
                ("user_dob", models.DateField()),
                ("user_gender", models.CharField(max_length=50)),
                ("user_phone", models.IntegerField()),
                ("user_quali", models.CharField(max_length=50)),
                ("user_remarks", models.CharField(max_length=200)),
                ("user_profile", models.ImageField(upload_to="image/")),
                ("user_file", models.FileField(upload_to="file/")),
                ("user_password", models.CharField(max_length=15)),
            ],
        ),
    ]
