# Generated by Django 5.2 on 2025-05-01 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aadhar",
            name="aadhar",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="aadhar_no",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="myapp.aadhar",
                to_field="aadhar",
            ),
        ),
    ]
