# Generated by Django 5.2 on 2025-05-07 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_aadhar_aadhar_alter_user_aadhar_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dep_name", models.CharField(max_length=50, unique=True)),
                ("dep_des", models.TextField(max_length=200)),
                ("dep_hod", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="aadhar_no",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_info",
                to="myapp.aadhar",
                to_field="aadhar",
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_name", models.CharField(max_length=50)),
                ("stu_email", models.EmailField(max_length=254)),
                (
                    "stu_dep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depart",
                        to="myapp.department",
                        to_field="dep_name",
                    ),
                ),
            ],
        ),
    ]
