# Generated by Django 5.2 on 2025-05-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_fuel_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="fuel_type",
            field=models.ManyToManyField(related_name="Vehicle", to="myapp.fuel"),
        ),
    ]
