# Generated by Django 5.2 on 2025-05-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_vehicle_fuel_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_name",
            field=models.CharField(max_length=50),
        ),
    ]
